# Generated by Django 3.2.3 on 2021-05-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='location',
            field=models.CharField(choices=[('AM', 'Assam'), ('BG', 'Bangalore'), ('DL', 'Delhi'), ('GZ', 'Ghaziabad'), ('GJ', 'Gujrat'), ('KL', 'Kerala'), ('MU', 'Mumbai'), ('ND', 'Noida'), ('PU', 'Pune'), ('TN', 'Tamil Nadu')], default=1, max_length=255),
        ),
    ]
