# Generated by Django 3.2.3 on 2021-05-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userinfo_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='gender_preference',
            new_name='preffered_gender',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='preffered_age_group',
            field=models.CharField(choices=[(1, 'Young'), (2, 'Older'), (3, 'Old')], default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='preffered_location',
            field=models.CharField(choices=[('AM', 'Assam'), ('BG', 'Bangalore'), ('DL', 'Delhi'), ('GZ', 'Ghaziabad'), ('GJ', 'Gujrat'), ('KL', 'Kerala'), ('MU', 'Mumbai'), ('ND', 'Noida'), ('PU', 'Pune'), ('TN', 'Tamil Nadu')], default=1, max_length=255),
        ),
    ]
