# Generated by Django 3.2.3 on 2021-05-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210530_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='preffered_age_group',
            field=models.CharField(choices=[('Y', 'Young'), ('O', 'Older'), ('O+', 'Old')], default=1, max_length=255),
        ),
    ]
