# Generated by Django 3.2.3 on 2021-05-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210531_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender'), ('NB', 'non-binary')], default=2, max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='location',
            field=models.CharField(choices=[('AM', 'Assam'), ('BG', 'Bangalore'), ('DL', 'Delhi'), ('GZ', 'Ghaziabad'), ('GJ', 'Gujrat'), ('KL', 'Kerala'), ('MU', 'Mumbai'), ('ND', 'Noida'), ('PU', 'Pune'), ('TN', 'Tamil Nadu')], default=2, max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='preffered_age_group',
            field=models.CharField(choices=[('Y', 'Young'), ('O', 'Older'), ('O+', 'Old')], default=2, max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='preffered_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'All')], default=2, max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='preffered_location',
            field=models.CharField(choices=[('AM', 'Assam'), ('BG', 'Bangalore'), ('DL', 'Delhi'), ('GZ', 'Ghaziabad'), ('GJ', 'Gujrat'), ('KL', 'Kerala'), ('MU', 'Mumbai'), ('ND', 'Noida'), ('PU', 'Pune'), ('TN', 'Tamil Nadu')], default=2, max_length=255),
        ),
    ]
