# Generated by Django 3.2.2 on 2021-06-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210531_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='preffered_age_group',
            field=models.CharField(choices=[('Y', 'Young'), ('O', 'Older'), ('E', 'Old')], default='Y', max_length=255),
        ),
    ]
