# Generated by Django 3.2.3 on 2021-06-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_userinfo_preffered_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='location',
            field=models.CharField(choices=[('NAM', 'Assam'), ('SBG', 'Bangalore'), ('NDL', 'Delhi'), ('NGZ', 'Ghaziabad'), ('NGJ', 'Gujrat'), ('SKL', 'Kerala'), ('SMU', 'Mumbai'), ('NND', 'Noida'), ('NPU', 'Pune'), ('NTN', 'Tamil Nadu')], default='NAM', max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='preffered_location',
            field=models.CharField(choices=[('NAM', 'Assam'), ('SBG', 'Bangalore'), ('NDL', 'Delhi'), ('NGZ', 'Ghaziabad'), ('NGJ', 'Gujrat'), ('SKL', 'Kerala'), ('SMU', 'Mumbai'), ('NND', 'Noida'), ('NPU', 'Pune'), ('NTN', 'Tamil Nadu')], default='NAM', max_length=255),
        ),
    ]
