# Generated by Django 3.2.3 on 2021-07-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_userinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='location',
            field=models.CharField(choices=[('Assam', 'Assam'), ('Bangalore', 'Bangalore'), ('Delhi', 'Delhi'), ('Ghaziabad', 'Ghaziabad'), ('Gujrat', 'Gujrat'), ('Kerala', 'Kerala'), ('Mumbai', 'Mumbai'), ('Noida', 'Noida'), ('Pune', 'Pune'), ('Tamil Nadu', 'Tamil Nadu')], default='Assam', max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='preffered_location',
            field=models.CharField(choices=[('Assam', 'Assam'), ('Bangalore', 'Bangalore'), ('Delhi', 'Delhi'), ('Ghaziabad', 'Ghaziabad'), ('Gujrat', 'Gujrat'), ('Kerala', 'Kerala'), ('Mumbai', 'Mumbai'), ('Noida', 'Noida'), ('Pune', 'Pune'), ('Tamil Nadu', 'Tamil Nadu')], default='Assam', max_length=255),
        ),
    ]
