# Generated by Django 3.2.4 on 2021-06-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='Second_user_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='current_user_id',
        ),
        migrations.AddField(
            model_name='room',
            name='Second_user',
            field=models.EmailField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='room',
            name='current_user',
            field=models.EmailField(default='', max_length=1000),
        ),
    ]
