# Generated by Django 3.2.4 on 2021-06-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_auto_20210620_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='Second_user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='current_user',
        ),
    ]
